replicaCount: 1

image:
  repository: axelkangou4791/go-web-app1
  pullPolicy: IfNotPresent
  tag: 14550431952

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific 



